### ISSUE TITLE
Make various secret keys configurable

### ISSUE THREAD

**Issue by flamarion** [wandb/helm-charts#249]
Today, when a customer informs a secret name to pull MySQL credentials, the Secret Key is fixed with [MYSQL_PASSWORD](https://github.com/wandb/helm-charts/blob/main/charts/operator-wandb/charts/app/templates/_deployment.tpl#L65).
For customers with dynamic secrets provisioning, this is a problem, given the secret key names are dynamically generated.

**Comment by abhinavg6** [comment]
Whatever we implement here should be done for Bucket, Redis and any other credentials as well.

**Comment by amanpruthi** [comment]
https://github.com/wandb/helm-charts/pull/257
